services:
  neo4j:
    image: neo4j:2025.10.1
    hostname: neo4j
    ports:
      - ${NEO4J_HTTP_PORT}:7474
      - ${NEO4J_BOLT_PORT}:7687
    volumes:
      - neo4j:/data
      - ./configurations/neo4j/init.cypher:/import/init.cypher
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_usage__report_enabled=false
      - NEO4J_db_query_default__language=CYPHER_25
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_initializer_neo4j_0=CALL apoc.cypher.runSchemaFile("init.cypher")


volumes:
  neo4j:
    name: neo4j