name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build Project
        run: ./gradlew assemble
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

  pmd:
    name: PMD Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run PMD Analysis
        run: ./gradlew pmdMain

  checkstyle:
    name: Checkstyle Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      neo4j:
        image: neo4j:5
        env:
          NEO4J_AUTH: none
          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "cypher-shell 'RETURN 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Unit Tests
        run: ./gradlew test
        env:
          QUARKUS_NEO4J_URI: bolt://localhost:7687
          QUARKUS_NEO4J_AUTHENTICATION_DISABLED: true

  docker-image-jvm:
    name: Docker image JVM
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [checkstyle, pmd, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Push Image
        uses: explorviz/deployment/.github/actions/build-and-deploy-quarkus-jvm@main
        with:
          platforms: "linux/amd64,linux/arm64/v8"
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ vars.DOCKER_JVM_IMAGE_NAME }}
          image-tag: "latest"
